#!/usr/bin/env python3
"""Extract all 48 icon bitmaps from SCORCH.EXE as JavaScript arrays."""

import sys

EXE = 'earth/SCORCH.EXE'
ICON_BASE_DS = 0x3826
DS_FILE_BASE = 0x055D80  # DS segment file base
STRIDE = 125
NUM_ICONS = 48

with open(EXE, 'rb') as f:
    data = f.read()

icon_base = DS_FILE_BASE + ICON_BASE_DS

print("// Icon bitmap data extracted from SCORCH.EXE DS:0x3826")
print("// 48 icons × 125 bytes each (type, width, height, pixels[122])")
print("// Pixel data is column-major: pixels[col * height + row], 0=transparent, nonzero=filled")
print("// Generated by disasm/extract_icons_js.py")
print()
print("export const ICONS = [")

for i in range(NUM_ICONS):
    off = icon_base + i * STRIDE
    ptype = data[off]
    width = data[off + 1]
    height = data[off + 2]
    pixels = data[off + 3 : off + 3 + width * height] if width > 0 and height > 0 else b''

    # Convert pixels to 0/1 array
    px_arr = [1 if b else 0 for b in pixels]

    if width == 0 or height == 0:
        print(f"  /* {i:2d} */ {{ t:{ptype}, w:{width}, h:{height}, px:[] }},")
    else:
        px_str = ','.join(str(b) for b in px_arr)
        print(f"  /* {i:2d} */ {{ t:{ptype}, w:{width}, h:{height}, px:[{px_str}] }},")

print("];")
